name: provider_app
description: A Flutter MVP for home service providers
version: 1.0.0+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.2.7
  
  # UI/UX
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  
  # Utilities
  intl: ^0.20.2
  http: ^1.1.0
  uuid: ^4.1.0
  
  # Navigation
  go_router: ^12.1.1
  
  # State Management
  provider: ^6.0.5
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true