name: provider_app
description: A Flutter MVP for home service providers
version: 1.0.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # Firebase & Backend Integration
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.2.7
  
  # HTTP & API
  http: ^0.13.5
  
  # State Management
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  
  # Location & Maps
  geolocator: ^14.0.1
  google_maps_flutter: ^2.6.1
  geocoding: ^4.0.0
  
  # Media & UI
  image_picker: ^1.0.7
  intl: ^0.17.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true