// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvK8M2N3P4Q5R6S7T8U9V0W1X2Y3Z4A5B',
    appId: '1:234567890123:web:1a2b3c4d5e6f7g8h',
    messagingSenderId: '234567890123',
    projectId: 'homelink-ghana-provider',
    authDomain: 'homelink-ghana-provider.firebaseapp.com',
    storageBucket: 'homelink-ghana-provider.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6D7E8F9G0H1I2J3K4L5M6N7O8P9Q0R1S',
    appId: '1:234567890123:android:2b3c4d5e6f7g8h9i',
    messagingSenderId: '234567890123',
    projectId: 'homelink-ghana-provider',
    storageBucket: 'homelink-ghana-provider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyE2F3G4H5I6J7K8L9M0N1O2P3Q4R5S6T7U',
    appId: '1:234567890123:ios:3c4d5e6f7g8h9i0j',
    messagingSenderId: '234567890123',
    projectId: 'homelink-ghana-provider',
    iosBundleId: 'com.homelink.provider.app',
    storageBucket: 'homelink-ghana-provider.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyE2F3G4H5I6J7K8L9M0N1O2P3Q4R5S6T7U',
    appId: '1:234567890123:ios:3c4d5e6f7g8h9i0j',
    messagingSenderId: '234567890123',
    projectId: 'homelink-ghana-provider',
    iosBundleId: 'com.homelink.provider.app',
    storageBucket: 'homelink-ghana-provider.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvK8M2N3P4Q5R6S7T8U9V0W1X2Y3Z4A5B',
    appId: '1:234567890123:web:1a2b3c4d5e6f7g8h',
    messagingSenderId: '234567890123',
    projectId: 'homelink-ghana-provider',
    authDomain: 'homelink-ghana-provider.firebaseapp.com',
    storageBucket: 'homelink-ghana-provider.appspot.com',
  );
}